project:
  type: website

website:
  title: "Damon's Blog"
  navbar:
    right:
      - text: "About"
        href: https://damoncroberts.com
      - icon: github
        href: https://github.com/damoncharlesroberts
  page-footer:
    center: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2021-2023 Damon Charles Roberts</span>
      <span class="faux-block"><br>All content licensed under {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} [Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>

format:
  html:
    theme: 
      dark: ./assets/theme/dark.css
      light: ./assets/theme/light.css
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
